name: verify

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: main
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Clone ac-library
      uses: actions/checkout@v3
      with:
          repository: atcoder/ac-library
          path: ac-library
          sparse-checkout: atcoder
          

    - name: Run tests
      working-directory: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        CPLUS_INCLUDE_PATH: ${{ github.workspace }}/ac-library
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
