name: verify

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Clone ac-library
      uses: actions/checkout@v4
      with:
          repository: atcoder/ac-library
          path: ac-library

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        CPLUS_INCLUDE_PATH: ${{ github.workspace }}/ac-library
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
